apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "cluster1"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "cluster1"
    spec:
      containers:
        - name: "cluster1"
          image: "tigptcronjobs.azurecr.io/cluster1"
          ports:
          - containerPort: 80